/* ARKT — contenu (données projets, équipe, témoignages, offre) */
window.ARKT = {
  email: "hello@arkt-conseil.com",

  nav: [
    { id: "projets", label: "Projets" },
    { id: "approche", label: "Approche" },
    { id: "offre", label: "Offre" },
    { id: "equipe", label: "Équipe" },
    { id: "contact", label: "Contact" },
  ],

  clients: ["Nike", "Puma", "Airbnb", "Pernod Ricard", "Patta", "Taster", "Selency", "Twicy", "Capsule", "Spilow", "KUBE", "La Meulerie"],

  moments: [
    { k: "01", t: "Je lance", d: "Un concept, un lieu, une marque. Donner le bon cap dès le premier jour." },
    { k: "02", t: "Je repositionne", d: "Montée en gamme, nouveau cap. Réaligner le discours sur l'ambition." },
    { k: "03", t: "Je change de dimension", d: "Structurer la marque pour grandir, sans se diluer." },
  ],

  /* ---------- coups de cœur (grand format, scroll horizontal) ---------- */
  featured: [
    {
      id: "horsdoeuvre",
      name: "Hors d'Œuvre",
      year: "2026",
      tag: "Food studio · événementiel",
      claim: "Repenser le traiteur événementiel comme un studio de création.",
      accentName: "#FF5C00",
      panels: [
        { kind: "intro", label: "Coup de cœur", title: "HORS D'ŒUVRE – 2026", sub: "Food studio · événementiel" },
        { kind: "text", head: "Contexte", body: "Repenser le traiteur événementiel comme un studio de création. Ni traiteur classique, ni restaurant éphémère, ni agence : construire une marque food premium qui existe à la croisée de la gastronomie, de la direction artistique et de la scénographie, et qui peut se poser au même niveau que les studios de design ou les maisons créatives." },
        { kind: "media", phr: "4/5", caption: "Hors d'Œuvre · identité", src: "arkt/images/horsdoeuvre-1.jpg" },
        { kind: "media", phr: "4/5", caption: "Hors d'Œuvre · palette", src: "arkt/images/horsdoeuvre-4.jpg" },
        { kind: "text", head: "Ce qu'on a fait", body: "Construction complète de la marque, de la plateforme à l'exécution. Positionnement « food studio », naming et écriture éditoriale, identité visuelle massive et inclinée, palette signature (orange incandescent, noir, chrome, bleu électrique), système de déclinaisons du logo et déploiement print sur l'ensemble des supports événementiels." },
        { kind: "media", phr: "4/5", caption: "Hors d'Œuvre · déploiement", src: "arkt/images/horsdoeuvre-5.jpg" },
        { kind: "media", phr: "4/5", caption: "Hors d'Œuvre · print", src: "arkt/images/horsdoeuvre-6.jpg" },
        { kind: "media", phr: "4/5", caption: "Hors d'Œuvre · événement", src: "arkt/images/horsdoeuvre-7.jpg" },
        { kind: "media", phr: "4/5", caption: "Hors d'Œuvre · scénographie", src: "arkt/images/horsdoeuvre-8.jpg" },
        { kind: "result", metric: "Premium", unit: "& éditorial", line: "Une marque qui s'installe d'emblée sur un registre premium et éditorial, immédiatement reconnaissable dans un univers traiteur habituellement générique. Une identité qui distingue Hors d'Œuvre dès la première impression." },
      ],
    },
    {
      id: "ciaomisu",
      name: "CiaoMisu!",
      year: "2026",
      tag: "Food & retail · Marseille",
      claim: "Faire naître à Marseille la première adresse entièrement dédiée au tiramisu et en faire un concept lifestyle à part entière.",
      accentName: "#E85A78",
      panels: [
        { kind: "intro", label: "Coup de cœur", title: "CIAOMISU! – 2026", sub: "Food & retail – Marseille" },
        { kind: "text", head: "Contexte", body: "Une recette familiale de tiramisu, une ambition claire : faire naître à Marseille la première adresse entièrement dédiée à ce dessert et en faire un concept lifestyle à part entière." },
        { kind: "media", phr: "4/5", caption: "Devanture Ciaomisu!", src: "arkt/images/ciaomisu-1.jpg" },
        { kind: "text", head: "Ce qu'on a fait", body: "Construction complète du projet, du concept à l'ouverture. Plateforme de marque et positionnement, naming, direction artistique rétro et gourmande, mascotte et identité visuelle, conception du point de vente, stratégie de lancement mêlant activation digitale, influence et presse." },
        { kind: "media", phr: "4/5", caption: "Mascotte Ciaomisu!", src: "arkt/images/ciaomisu-2.jpg" },
        { kind: "media", phr: "4/5", caption: "Intérieur Ciaomisu!", src: "arkt/images/ciaomisu-3.jpg" },
        { kind: "result", metric: "+3K", unit: "abonnés", line: "Une ouverture remarquée dans le 8e, une couverture presse immédiate (Toutma, L'Essentiel, Marseille Secrète), et un concept déjà identifié comme la référence tiramisu de Marseille." },
      ],
    },
    {
      id: "meulerie",
      name: "La Meulerie",
      year: "2021",
      tag: "Cofondé par ARKT",
      claim: "La preuve qu'ARKT ne fait pas que conseiller : le cabinet construit.",
      accentName: "#F2B705",
      panels: [
        { kind: "intro", label: "Coup de cœur", title: "La Meulerie", sub: "Le bon fromage, rendu désirable. Porté par l'énergie de Marseille." },
        { kind: "text", head: "Contexte", body: "Rendre le bon fromage accessible et désirable, sur un marché (la fromagerie) perçu comme traditionnel et figé. Tout réinventer : le ton, le lieu, la communauté." },
        { kind: "media", phr: "16/10", caption: "Duo fondateurs · scooter jaune", src: "arkt/images/meulerie-1.jpg" },
        { kind: "text", head: "Ce qu'on a fait", body: "Une marque forte et un univers coloré, inclusif, où tout le monde se sent bien. Un concept fédérateur : joie de vivre, partage, simplicité. Une communauté engagée, une communication digitale affirmée, des partenariats audacieux, un déploiement retail." },
        { kind: "media", phr: "3/4", caption: "Devanture jaune « FROMAGERIE »", src: "arkt/images/meulerie-2.jpg" },
        { kind: "media", phr: "3/4", caption: "Néon « Say Cheese »", src: "arkt/images/meulerie-3.jpg" },
        { kind: "result", metric: "4", unit: "boutiques", line: "Lancées à Marseille en moins de 3 ans. Franchise en cours, et un rayonnement bien au-delà des points de vente grâce à la communauté." },
      ],
    },
    {
      id: "airbnb",
      name: "Airbnb",
      year: "2026",
      tag: "Airbnb Experiences · Paris",
      claim: "Quand une marque mondiale confie à ARKT la projection de ses utilisateurs.",
      accentName: "#FF385C",
      panels: [
        { kind: "intro", label: "Coup de cœur", title: "Airbnb", sub: "Faire émerger le désir autour des Airbnb Experiences à Paris." },
        { kind: "text", head: "Contexte", body: "Faire naître le désir et la projection chez les utilisateurs autour des Airbnb Experiences à Paris, dans un environnement dominé par le format vidéo court." },
        { kind: "media", phr: "9/16", caption: "Airbnb Experiences · marque", src: "arkt/images/airbnb-1.jpg" },
        { kind: "text", head: "Ce qu'on a fait", body: "Définition d'une stratégie de contenu et d'acquisition centrée sur les formats vidéo courts. Analyse des codes performants. Création de concepts éditoriaux capables de générer du désir et de la projection." },
        { kind: "media", phr: "9/16", caption: "App host · vue programme", src: "arkt/images/airbnb-2.jpg" },
        { kind: "media", phr: "9/16", caption: "Expérience · The French Bastards", src: "arkt/images/airbnb-3.jpg" },
        { kind: "result", metric: "Désir", unit: "& projection", line: "Une mécanique éditoriale pensée pour la performance vidéo courte, conçue pour transformer l'attention en projection. Métriques de campagne à venir." },
      ],
    },
  ],

  /* ---------- grille (déploiement au clic) ---------- */
  grid: [
    { id: "nb1", name: "NB1", year: "2026", phr: "4/5", short: "Vidéos produit · campagne ads",
      logo: "arkt/images/nb1-logo.jpg",
      photos: [
        { video: "arkt/videos/nb1-driss.mp4", poster: "arkt/videos/nb1-driss.jpg" },
        { video: "arkt/videos/nb1-suzane.mp4", poster: "arkt/videos/nb1-suzane.jpg" },
        { video: "arkt/videos/nb1-karine.mp4", poster: "arkt/videos/nb1-karine.jpg" },
        { video: "arkt/videos/nb1-jo-1.mp4" },
        { video: "arkt/videos/nb1-jo-4.mp4" },
        { video: "arkt/videos/nb1-suzane-1.mp4" },
        { video: "arkt/videos/nb1-karine-3.mp4" },
      ],
      tags: ["Production vidéo", "Contenu ads", "Acquisition", "Communication"],
      body: "Production de contenus vidéo pour NB1 : tournages produit et création de formats publicitaires pour leur campagne de communication et d'acquisition." },
    { id: "palauma", name: "Palauma", year: "2026", phr: "4/5", short: "Outsider d'un immobilier standardisé",
      logo: "arkt/images/palauma-logo.jpg",
      photos: ["arkt/images/palauma-1.jpg", "arkt/images/palauma-2.jpg", "arkt/images/palauma-3.jpg", "arkt/images/palauma-4.jpg", "arkt/images/palauma-5.jpg"],
      tags: ["Positionnement", "Storytelling", "Éditorial LinkedIn"],
      body: "Structuration du positionnement stratégique et du storytelling de Palauma Global Group : une posture différenciante d'outsider sur un marché immobilier standardisé, et une stratégie éditoriale LinkedIn pour renforcer visibilité et influence du groupe." },
    { id: "crousty", name: "Crousty Crew", year: "2026", phr: "4/5", short: "Pour Taster · street food",
      logo: "arkt/images/crousty-logo.jpg",
      photos: ["arkt/images/crousty-1.jpg", "arkt/images/crousty-2.jpg", "arkt/images/crousty-3.jpg", "arkt/images/crousty-4.jpg", "arkt/images/crousty-5.jpg", "arkt/images/crousty-6.jpg", "arkt/images/crousty-7.jpg"],
      tags: ["Plateforme de marque", "DA", "Codes retail & archi"],
      body: "Création de la plateforme de marque et de la direction artistique : positionnement différenciant dans la street food, identité inspirée des codes brigade et streetwear, développement des codes architecturaux et retail pour un déploiement physique cohérent et durable." },
    { id: "vitamine", name: "Vitamine", year: "2026", phr: "4/5", short: "Breakfast Club · rituel d'entreprise",
      logo: "arkt/images/vitamine-logo.jpg",
      photos: ["arkt/images/vitamine-1.jpg", "arkt/images/vitamine-2.jpg", "arkt/images/vitamine-3.jpg", "arkt/images/vitamine-4.jpg", "arkt/images/vitamine-5.jpg", "arkt/images/vitamine-6.jpg"],
      tags: ["Naming", "Plateforme de marque", "Identité visuelle", "DA"],
      body: "Création de la plateforme de marque, du naming et de l'identité visuelle de Vitamine Breakfast Club : direction artistique complète, positionnement centré sur le rituel collectif en entreprise, la performance et la convivialité." },
    { id: "pernodricard", name: "Pernod Ricard", year: "2026", phr: "4/5", short: "Maison Yellow · terrasse Ricard",
      logo: "arkt/images/pernodricard-logo.jpg",
      photos: ["arkt/images/pernodricard-1.jpg", "arkt/images/pernodricard-2.jpg", "arkt/images/pernodricard-3.jpg", "arkt/images/pernodricard-4.jpg", "arkt/images/pernodricard-5.jpg"],
      tags: ["Scénographie", "Design d'espace", "Expérientiel"],
      body: "Redesign stratégique et opérationnel de la terrasse de Maison Yellow pour Pernod Ricard : création d'un territoire expérientiel inspiré d'une place de village méditerranéenne, combinant scénographie, agencement, mobilier, végétalisation et codes visuels Ricard." },
    { id: "adriensusini", name: "Adrien Susini", year: "2026", phr: "4/5", short: "Chanteur corse · site web & univers artistique",
      logo: "arkt/images/adriensusini-logo.jpg",
      photos: ["arkt/images/adriensusini-1.jpg", "arkt/images/adriensusini-2.jpg", "arkt/images/adriensusini-3.jpg", "arkt/images/adriensusini-4.jpg"],
      tags: ["Site web", "Stratégie éditoriale", "Identité digitale"],
      body: "Conception et développement du site web d'Adrien Susini, chanteur corse, auteur-compositeur et interprète, pour structurer son univers artistique, valoriser son parcours de résilience, présenter sa musique, ses dates et faciliter la prise de contact avec programmateurs, journalistes et auditeurs." },
    { id: "estelletorossian", name: "Estelle Torossian", year: "2026", phr: "4/5", short: "Médecin esthétique · marque culturelle",
      logo: "arkt/images/estelletorossian-logo.jpg",
      photos: ["arkt/images/estelletorossian-1.jpg", "arkt/images/estelletorossian-2.jpg", "arkt/images/estelletorossian-3.jpg", "arkt/images/estelletorossian-4.jpg", "arkt/images/estelletorossian-5.jpg"],
      tags: ["Stratégie de contenu", "Image de marque", "Éditorial"],
      body: "Définition d'une stratégie de contenu et d'image pour le Dr Estelle Torossian, médecin esthétique à Marseille : transformer une expertise médicale haut de gamme en marque culturelle capable de parler à une audience plus jeune et plus connectée, en associant précision scientifique, humour, pop culture et désirabilité." },
    { id: "egoz", name: "Egoz", year: "2026", phr: "4/5", short: "Marque · stratégie & identité",
      logo: "arkt/images/egoz-logo.jpg",
      photos: ["arkt/images/egoz-1.jpg", "arkt/images/egoz-2.jpg", "arkt/images/egoz-3.jpg", "arkt/images/egoz-4.jpg", "arkt/images/egoz-5.jpg"],
      tags: ["Stratégie de marque", "Identité visuelle"],
      body: "Accompagnement stratégique et identitaire." },
    { id: "caparle", name: "Ça Parle", year: "2026", phr: "4/5", short: "Communication · stratégie éditoriale",
      logo: "arkt/images/caparle-logo.jpg",
      photos: ["arkt/images/caparle-1.jpg", "arkt/images/caparle-2.jpg", "arkt/images/caparle-3.jpg", "arkt/images/caparle-4.jpg", "arkt/images/caparle-5.jpg"],
      tags: ["Stratégie éditoriale", "Communication"],
      body: "Stratégie éditoriale et de communication." },
    { id: "capsule", name: "Capsule", year: "2025", phr: "4/5", short: "Salle de Pilates Reformer · Marseille",
      logo: "arkt/images/capsule-logo.jpg",
      photos: ["arkt/images/capsule-1.jpg", "arkt/images/capsule-2.jpg", "arkt/images/capsule-3.jpg", "arkt/images/capsule-4.jpg", "arkt/images/capsule-5.jpg"],
      tags: ["Naming", "Identité & DA", "Site web", "Positionnement", "Contenu & lancement"],
      body: "Lancement d'une salle de Pilates Reformer à Marseille. Naming, charte visuelle et direction artistique, création du site web, stratégie de positionnement et de communication, stratégie de contenu et de lancement digital." },
    { id: "kube", name: "Kube", year: "2025", phr: "4/5", short: "Bootcamp nouvelle génération · Marseille",
      logo: "arkt/images/kube-logo.jpg",
      photos: ["arkt/images/kube-1.jpg", "arkt/images/kube-2.jpg", "arkt/images/kube-3.jpg", "arkt/images/kube-4.jpg", "arkt/images/kube-5.jpg", "arkt/images/kube-6.jpg"],
      tags: ["Charte de marque", "Identité & ton", "Persona", "Stratégie social"],
      body: "Bootcamp nouvelle génération à Marseille. Définition de la charte de marque, de l'identité visuelle et du ton of voice ; identification du persona et du positionnement ; stratégie réseaux sociaux et supervision de la production de contenus." },
    { id: "pattaxnike", name: "Patta × Nike", year: "2025", phr: "4/5", short: "Pop-up instore · scénographie",
      logo: "arkt/images/pattaxnike-logo.jpg",
      photos: ["arkt/images/pattaxnike-1.jpg", "arkt/images/pattaxnike-2.jpg", "arkt/images/pattaxnike-3.jpg", "arkt/images/pattaxnike-4.jpg", "arkt/images/pattaxnike-5.jpg"],
      tags: ["Scénographie", "Set design", "Activation marque"],
      body: "Imaginer et produire la scénographie instore du pop-up Nike x Patta chez SAISON, en traduisant l'esprit « Get Familiar » en moment de marque vivant." },
    { id: "nike", name: "Nike", year: "2025", phr: "4/5", short: "Total 90 · événement & set design",
      logo: "arkt/images/nike-logo.jpg",
      photos: ["arkt/images/nike-1.jpg", "arkt/images/nike-2.jpg", "arkt/images/nike-3.jpg", "arkt/images/nike-4.jpg"],
      tags: ["Événement", "Set design", "Influence locale"],
      body: "Organisation d'un événement d'influence locale et set design pour la réédition de la Total 90, modèle iconique de Nike, en exclusivité dans le magasin Saison à Marseille." },
    { id: "placedesfinances", name: "Place des Finances", year: "2025", phr: "4/5", short: "Insuretech marseillaise · rebranding",
      logo: "arkt/images/placedesfinances-logo.jpg",
      photos: ["arkt/images/placedesfinances-1.jpg", "arkt/images/placedesfinances-2.jpg", "arkt/images/placedesfinances-3.jpg", "arkt/images/placedesfinances-4.jpg", "arkt/images/placedesfinances-5.jpg"],
      tags: ["Rebranding", "Stratégie commerciale", "BtoC & BtoB"],
      body: "Rebranding et redéfinition de la stratégie de déploiement commercial BtoC et BtoB d'une insuretech marseillaise." },
    { id: "spilow", name: "Spilow", year: "2025", phr: "4/5", short: "Pilates Club · naming & branding · Aubagne",
      logo: "arkt/images/spilow-logo.jpg",
      photos: ["arkt/images/spilow-1.jpg", "arkt/images/spilow-2.jpg", "arkt/images/spilow-3.jpg", "arkt/images/spilow-4.jpg", "arkt/images/spilow-5.jpg"],
      tags: ["Naming", "Charte visuelle", "Positionnement", "Communication"],
      body: "Naming, charte visuelle, stratégie de positionnement et communication pour le lancement d'une salle de Pilates Reformer à Marseille." },
    { id: "lademeure", name: "La Demeure", year: "2025", phr: "4/5", short: "Boutique · rebranding suite à reprise",
      logo: "arkt/images/lademeure-logo.jpg",
      photos: ["arkt/images/lademeure-1.jpg", "arkt/images/lademeure-2.jpg", "arkt/images/lademeure-3.jpg", "arkt/images/lademeure-4.jpg", "arkt/images/lademeure-5.jpg", "arkt/images/lademeure-6.jpg"],
      tags: ["Rebranding", "Identité visuelle"],
      body: "Rebranding de la boutique suite à une reprise de l'enseigne en novembre 2024 : nouveau nom, nouvelle identité visuelle, repositionnement de l'offre." },
    { id: "puma", name: "Puma", year: "2025", phr: "4/5", short: "Set design retail · activation produit",
      logo: "arkt/images/puma-logo.jpg",
      photos: ["arkt/images/puma-1.jpg", "arkt/images/puma-2.jpg", "arkt/images/puma-3.jpg", "arkt/images/puma-4.jpg", "arkt/images/puma-5.jpg"],
      tags: ["Set design", "Retail", "Activation marque"],
      body: "Set design pour la mise en avant de produits Puma en point de vente retail." },
    { id: "ve", name: "Vé", year: "2024", phr: "4/5", short: "Glacier végétal · Marseille",
      logo: "arkt/images/ve-logo.jpg",
      photos: ["arkt/images/ve-1.jpg", "arkt/images/ve-2.jpg", "arkt/images/ve-3.jpg", "arkt/images/ve-4.jpg", "arkt/images/ve-5.jpg", "arkt/images/ve-6.jpg"],
      tags: ["Naming", "Charte visuelle", "Positionnement", "Communication"],
      body: "Naming, charte visuelle, stratégie de positionnement et communication pour un nouveau concept de glacier végétal à Marseille." },
    { id: "nailledit", name: "Nailed It", year: "2024", phr: "4/5", short: "Agence événementielle · naming & branding",
      logo: "arkt/images/nailledit-logo.jpg",
      photos: ["arkt/images/nailledit-1.jpg", "arkt/images/nailledit-2.jpg", "arkt/images/nailledit-3.jpg", "arkt/images/nailledit-4.jpg"],
      tags: ["Naming", "Charte visuelle", "Positionnement", "Communication"],
      body: "Naming, charte visuelle, stratégie de positionnement et communication pour une agence d'évènementiel d'entreprise." },
    { id: "apt20", name: "APT 20", year: "2024", phr: "4/5", short: "Coffee shop · design d'espace · Marseille",
      logo: "arkt/images/apt20-logo.jpg",
      photos: ["arkt/images/apt20-1.jpg", "arkt/images/apt20-2.jpg", "arkt/images/apt20-3.jpg", "arkt/images/apt20-4.jpg", "arkt/images/apt20-5.jpg", "arkt/images/apt20-6.jpg"],
      tags: ["Design d'espace"],
      body: "Design d'espace pour un coffee shop à Marseille." },
    { id: "richelieu", name: "Richelieu", year: "2024", phr: "4/5", short: "Chaussures haut de gamme · design d'espace",
      logo: "arkt/images/richelieu-logo.jpg",
      photos: ["arkt/images/richelieu-1.jpg", "arkt/images/richelieu-2.jpg", "arkt/images/richelieu-3.jpg", "arkt/images/richelieu-4.jpg", "arkt/images/richelieu-5.jpg", "arkt/images/richelieu-6.jpg", "arkt/images/richelieu-7.jpg", "arkt/images/richelieu-8.jpg"],
      tags: ["Design d'espace", "Merchandising", "Via Bart & Pucci"],
      body: "Design d'espace et stratégie de merchandising pour un magasin de chaussures et accessoires haut de gamme à Marseille." },
    { id: "twicy", name: "Twicy", year: "2024", phr: "4/5", short: "IT reconditionnée · stratégie & media",
      logo: "arkt/images/twicy-logo.jpg",
      photos: ["arkt/images/twicy-1.jpg", "arkt/images/twicy-2.jpg", "arkt/images/twicy-3.jpg", "arkt/images/twicy-4.jpg"],
      tags: ["Personal branding", "Communication", "Média", "Accompagnement continu"],
      body: "Accompagnement du dirigeant dans sa stratégie de personal branding et communication institutionnelle. Gestion complète de la stratégie de communication de la marque. Création du média The Big Reboot dédié aux experts du numérique responsable." },
    { id: "adsdesign", name: "ADS Design", year: "2024", phr: "4/5", short: "Design urbain · stratégie & marketing",
      logo: "arkt/images/adsdesign-logo.jpg",
      photos: ["arkt/images/adsdesign-1.jpg", "arkt/images/adsdesign-2.jpg", "arkt/images/adsdesign-3.jpg", "arkt/images/adsdesign-4.jpg", "arkt/images/adsdesign-5.jpg"],
      tags: ["Stratégie de communication", "Marketing opérationnel", "Accompagnement continu"],
      body: "Définition de la stratégie de communication de l'entreprise, management opérationnel de l'équipe marketing interne, coaching des dirigeants. Mise en place d'un écosystème tech dédié à l'acquisition et au suivi de la relation client." },
    { id: "linstantcryo", name: "L'Instant Cryo", year: "2024", phr: "4/5", short: "Institut cryo & minceur · stratégie franchise",
      logo: "arkt/images/linstantcryo-logo.jpg",
      photos: ["arkt/images/linstantcryo-1.jpg", "arkt/images/linstantcryo-2.jpg", "arkt/images/linstantcryo-3.jpg"],
      tags: ["Conseil stratégique", "Franchise", "Communication"],
      body: "Conseils stratégiques récurrents pour le développement d'une chaîne de franchises et la gestion opérationnelle des points de vente. Stratégie de communication pour le lancement de produits dérivés." },
    { id: "accesud", name: "Accesud", year: "2024", phr: "4/5", short: "Agence intérim · développement commercial",
      logo: "arkt/images/accesud-logo.jpg",
      photos: ["arkt/images/accesud-1.jpg", "arkt/images/accesud-2.jpg", "arkt/images/accesud-3.jpg"],
      tags: ["Conseil stratégique", "Développement commercial", "Branding"],
      body: "Conseils stratégiques pour le développement commercial d'une agence intérim basée à Marseille." },
    { id: "marymadeleine", name: "Mary Madeleine", year: "2023", phr: "4/5", short: "Chaîne de madeleines · naming & branding",
      logo: "arkt/images/marymadeleine-logo.jpg",
      photos: ["arkt/images/marymadeleine-1.jpg", "arkt/images/marymadeleine-2.jpg", "arkt/images/marymadeleine-3.jpg", "arkt/images/marymadeleine-4.jpg"],
      tags: ["Naming", "Identité visuelle", "Communication", "Lancement"],
      body: "Stratégie de positionnement, définition du nom, création du logo et de la charte graphique, communication durant la phase de lancement, pour une chaîne de magasins de madeleines à Marseille." },
    { id: "bartpucci", name: "Bart & Pucci", year: "2023", phr: "4/5", short: "Design d'espace · filiale ARKT",
      logo: "arkt/images/bartpucci-logo.jpg",
      photos: ["arkt/images/bartpucci-1.jpg", "arkt/images/bartpucci-2.jpg", "arkt/images/bartpucci-3.jpg"],
      tags: ["Design d'espace", "Scénographie", "Architecture intérieure"],
      body: "En association avec Camille Puccinelli, Bart & Pucci est la filiale de ARKT spécialisée dans l'agencement et le design d'espace. Accompagnement de clients professionnels dans la création de lieux et la scénographie, et de particuliers pour des projets de rénovation et gestion des travaux." },
    { id: "selency", name: "Selency", year: "2019", phr: "4/5", short: "Marketplace mobilier · pôle B2B",
      logo: "arkt/images/selency-logo.jpg",
      photos: ["arkt/images/selency-1.jpg", "arkt/images/selency-2.jpg", "arkt/images/selency-3.jpg"],
      tags: ["Développement commercial", "Stratégie", "B2B"],
      body: "Création et développement du pôle B2B de Selency (hospitality / offices / prescripteurs). Définition de la stratégie de développement et du prévisionnel chiffré puis mise en place des leviers marketing, commerciaux, RH, financiers et logistiques." },
    { id: "vestiairecollective", name: "Vestiaire Collective", year: "2017", phr: "4/5", short: "Marketplace luxe · acquisition & CRM",
      logo: "arkt/images/vestiairecollective-logo.jpg",
      photos: ["arkt/images/vestiairecollective-1.jpg", "arkt/images/vestiairecollective-2.jpg", "arkt/images/vestiairecollective-3.jpg"],
      tags: ["Acquisition", "CRM", "Communication"],
      body: "Gestion de la stratégie d'acquisition et d'engagement clients (campagnes CRM) sur les audiences de vendeurs et d'acheteurs, via les canaux physiques (événementiel, gifting) et digitaux (CRM, Ads, SEA, SEO, campagnes in-app)." },
  ],

  /* ---------- approche ---------- */
  approche: [
    { k: "01", t: "Analyse & diagnostic", d: "Comprendre le contexte, les enjeux, les objectifs, les contraintes. Avant tout, écouter." },
    { k: "02", t: "Structuration stratégique", d: "Positionnement, messages clés, angles de prise de parole, priorités. Donner une direction claire." },
    { k: "03", t: "Activation", d: "Mise en œuvre ciblée et cadrée, toujours alignée sur la stratégie. Là où la trajectoire prend vie.", opt: true },
  ],

  /* ---------- offre ----------
     3 offres en cartes. Un clic sur une carte ouvre un panneau `detail` sous les cartes :
     pains (les galères du dirigeant, dans ses mots), faire (ce qu'on fait, sans jargon),
     change (ce que ça change pour lui), puis un bouton vers le contact.
  */
  offreLead: "Trois façons de travailler ensemble, selon où vous en êtes : clarifier la direction, piloter dans la durée, activer ce qui a été décidé.",
  offre: [
    { id: "clarifier", name: "Clarifier", sub: "One-shot stratégique",
      quand: "Vous lancez un projet, repositionnez une marque, ou sentez que « ça part dans tous les sens ». Vous voulez arrêter de décider à l'instinct.",
      contenu: ["Diagnostic", "Positionnement", "Messages clés", "Priorités", "Angles de communication"],
      fin: "Une direction claire, et de quoi trancher.",
      detail: {
        pains: [
          "Vous lancez quelque chose et vous ne savez pas par où commencer.",
          "Vous faites plein de choses, mais vous avez l'impression que rien n'avance vraiment.",
          "Votre marque ne ressemble plus à ce que vous êtes devenu.",
          "Vous décidez au feeling, et vous sentez que ça vous coûte.",
        ],
        faire: "On prend le temps de comprendre votre activité, vos clients, et ce qui vous rend différent. Puis on met des mots simples dessus : ce que vous proposez, à qui, et pourquoi on devrait vous choisir vous. On termine par une restitution, en direct, où tout devient clair.",
        change: "Vous savez où vous allez. Vous pouvez dire non aux mauvaises idées. Et chaque euro que vous dépenserez ensuite en communication servira à quelque chose.",
      } },
    { id: "piloter", name: "Piloter", sub: "Direction marketing externalisée",
      quand: "Vous avez une équipe ou des prestataires, mais pas de cap clair ni de pilotage. Les actions s'enchaînent sans cohérence.",
      contenu: ["Points mensuels de pilotage", "Arbitrages", "Validation des actions", "Cohérence globale", "Coordination des parties prenantes"],
      fin: "Un cerveau stratégique externalisé : arbitrage, priorisation, décision.",
      detail: {
        pains: [
          "Vous avez un freelance, une agence, un alternant… mais personne ne coordonne.",
          "Vous passez vos soirées à valider des posts au lieu de diriger votre boîte.",
          "Chaque prestataire tire dans sa direction, et vous au milieu.",
          "Vous ne savez pas si ce que vous payez sert vraiment à quelque chose.",
        ],
        faire: "On devient votre directeur marketing, sans que vous ayez à en embaucher un. Chaque mois, on regarde ensemble ce qui a été fait, ce qui marche, et on décide de la suite. Entre deux, c'est nous qui parlons à vos prestataires, qui tranchons, et qui disons non à ce qui ne sert pas votre cap.",
        change: "Vous retrouvez du temps. Il n'y a plus qu'une seule direction. Et vous arrêtez de payer pour des choses qui ne servent à rien.",
      } },
    { id: "activer", name: "Activer", sub: "Exécution cadrée",
      quand: "Vous voulez un interlocuteur unique et éviter la dispersion entre prestataires.",
      contenu: ["Contenu & community management", "Identité visuelle & charte graphique", "Site internet"],
      fin: "Toujours dans le prolongement d'un cadrage stratégique.",
      detail: {
        pains: [
          "Vous voulez un site, des contenus, une identité… mais pas gérer trois prestataires.",
          "Vous avez déjà eu un logo ou un site qui « ne ressemblait à rien », parce que personne n'avait de vision d'ensemble.",
          "Vous voulez que ce soit fait, bien fait, sans y passer vos soirées.",
        ],
        faire: "On produit ce qui a été décidé, avec des gens qu'on connaît et qu'on pilote : contenus et réseaux sociaux, identité visuelle, site internet. Vous avez un seul interlocuteur, un planning clair, et un aller-retour pour ajuster. Et comme on connaît votre stratégie, tout est cohérent dès le départ.",
        change: "C'est fait, c'est cohérent, et vous n'avez qu'un seul numéro à appeler.",
      } },
  ],

  /* ---------- témoignages (verbatims réels) ---------- */
  testimonials: [
    { name: "Julien Raynal", role: "CEO de Twicy", img: "https://framerusercontent.com/images/zE2BUbJcEjtHSkGL4KeMPa2SGho.png?width=828&height=782",
      quote: "Travailler avec ARKT est un vrai atout pour Twicy. Leur capacité à s'immerger rapidement dans notre business model leur permet de produire des contenus qui apportent une réelle valeur à nos clients : ils comprennent notre activité, nos enjeux et nos partenaires, avec une fluidité impressionnante, comme s'ils faisaient partie intégrante de l'entreprise. ARKT est un partenaire clé pour notre croissance.",
      hi: ["un vrai atout pour Twicy", "comme s'ils faisaient partie intégrante de l'entreprise", "un partenaire clé pour notre croissance"] },
    { name: "Maxime Brousse", role: "CEO de Selency", img: "https://framerusercontent.com/images/TybSV8UwyID2kF9mPEmMzyQQjA.webp?width=258&height=246",
      quote: "Arthur a construit le service pro de Selency, un pôle stratégique devenu un véritable levier de croissance pour la marque. Je le recommande pour sa capacité à innover, construire et pérenniser des projets complexes et stratégiques.",
      hi: ["un véritable levier de croissance", "innover, construire et pérenniser"] },
    { name: "Barbara Adinany", role: "CEO de L'Instant Cryo", img: "https://framerusercontent.com/images/sOBFIcV4MtSCAIFtHtmi0ElYmA.jpg?width=764&height=1135",
      quote: "Arthur possède une expertise dingue en matière de conception et développement stratégique. Grâce à sa grande capacité à comprendre mes besoins, nos collaborations régulières sont fluides et efficaces.",
      hi: ["une expertise dingue", "fluides et efficaces"] },
    { name: "Christophe Alloun", role: "Fondateur de Vé!", img: "https://framerusercontent.com/images/ABvRzJ5B6cOy4isg2lH8O3YAmY.png?width=470&height=481",
      quote: "Quand on a décidé d'ouvrir notre glacier, on nous a tout de suite recommandé ARKT pour créer notre identité. Nous savions exactement ce que nous ne voulions pas, et Arthur a parfaitement compris ce qu'il nous fallait. Chaque fois que j'entends « Vé, ton glacier comme il est beau », je dis merci Arthur.",
      hi: ["on nous a tout de suite recommandé ARKT", "a parfaitement compris ce qu'il nous fallait"] },
  ],

  /* ---------- équipe ---------- */
  team: [
    { name: "Arthur Barret", role: "Founder & CEO", img: "https://framerusercontent.com/images/rb4UNclQQsvqth0gNNBep2r4jHg.png?width=1436&height=1434",
      bio: "+10 ans à la tête de directions marketing & commerciales : Vestiaire Collective, Selency. Cofondateur du concept food La Meulerie." },
    { name: "Tobias Simon", role: "Consultant Marketing", img: "https://framerusercontent.com/images/XXlxtuXS3aS1YGtBgxtvWp8eA.jpeg?width=717&height=601",
      bio: "Coordination clients, gestion des projets récurrents, growth strategy." },
    { name: "Mickaël Guagenti", role: "Consultant Marketing", img: "https://framerusercontent.com/images/wwCV3juDZzvq7vIgGLzKbvVCtM.jpeg?width=800&height=800",
      bio: "Création de contenu vidéo & réseaux sociaux, stratégie marketing, DA." },
    { name: "Driss Azzoug", role: "Consultant Pop Culture", img: "https://framerusercontent.com/images/CjN28LCNrCmOmsN9OiwjmEZaU.jpg?width=656&height=686",
      bio: "Veille pop culture, direction créative." },
  ],
};
