/* ARKT — contenu (données projets, équipe, témoignages, offre) */
window.ARKT = {
  email: "hello@arkt-conseil.com",

  nav: [
    { id: "projets", label: "Projets" },
    { id: "approche", label: "Approche" },
    { id: "offre", label: "Offre" },
    { id: "equipe", label: "Équipe" },
    { id: "contact", label: "Contact" },
  ],

  clients: ["Nike", "Puma", "Airbnb", "Pernod Ricard", "Patta", "Taster", "Selency", "Twicy", "Capsule", "Spilow", "KUBE", "La Meulerie"],

  moments: [
    { k: "01", t: "Je lance", d: "Un concept, un lieu, une marque. Donner le bon cap dès le premier jour." },
    { k: "02", t: "Je repositionne", d: "Montée en gamme, nouveau cap. Réaligner le discours sur l'ambition." },
    { k: "03", t: "Je change de dimension", d: "Structurer la marque pour grandir, sans se diluer." },
  ],

  /* ---------- coups de cœur (grand format, scroll horizontal) ---------- */
  featured: [
    {
      id: "horsdoeuvre",
      story: { clarifier: "Hors d'Œuvre est arrivé avec une intuition forte et pas de cadre : ni traiteur classique, ni restaurant éphémère, ni agence. **On a d'abord clarifié ce que la marque devait être : un ==food studio==**, à la croisée de la gastronomie, de la direction artistique et de la scénographie, qui se pose au même niveau qu'une ==maison créative==. De ce positionnement découlent le naming, le ton éditorial et les priorités de lancement.",
        piloter: "On a ensuite piloté la construction de la marque de bout en bout, en arbitrant chaque choix (identité, contenus, prises de parole) à l'aune de ce ==positionnement premium==, **pour qu'aucune pièce ne fasse retomber l'ensemble dans le registre traiteur générique**.",
        activer: "**Et on a créé tout ce qui rend la marque visible** : une ==identité visuelle massive et inclinée==, une palette signature, un système de déclinaisons du logo et son déploiement print sur l'ensemble des supports événementiels. Puis la ligne éditoriale, la direction artistique des shootings, ==les shootings eux-mêmes== et l'animation des réseaux sociaux, pour que la marque vive au quotidien avec la même exigence que le jour de son lancement.",
        resultat: "**une marque premium et éditoriale**, ==reconnaissable dès la première impression==, dans un univers habituellement interchangeable." },
      name: "Hors d'Œuvre",
      year: "2026",
      tag: "Food studio · événementiel",
      claim: "Repenser le traiteur événementiel comme un studio de création.",
      accentName: "#FF5C00",
      logo: "arkt/images/horsdoeuvre-logo.jpg",
      panels: [
        { kind: "intro", label: "Coup de cœur", title: "HORS D'ŒUVRE – 2026", sub: "Food studio · événementiel" },
        { kind: "video", src: "arkt/videos/horsdoeuvre-1.mp4", poster: "arkt/videos/horsdoeuvre-1.jpg" },
        { kind: "text", head: "Contexte", body: "Repenser le traiteur événementiel comme un studio de création. Ni traiteur classique, ni restaurant éphémère, ni agence : construire une marque food premium qui existe à la croisée de la gastronomie, de la direction artistique et de la scénographie, et qui peut se poser au même niveau que les studios de design ou les maisons créatives." },
        { kind: "media", phr: "4/5", caption: "Hors d'Œuvre · identité", src: "arkt/images/horsdoeuvre-1.jpg" },
        { kind: "media", phr: "4/5", caption: "Hors d'Œuvre · palette", src: "arkt/images/horsdoeuvre-4.jpg" },
        { kind: "text", head: "Ce qu'on a fait", body: "Construction complète de la marque, de la plateforme à l'exécution. Positionnement « food studio », naming et écriture éditoriale, identité visuelle massive et inclinée, palette signature (orange incandescent, noir, chrome, bleu électrique), système de déclinaisons du logo et déploiement print sur l'ensemble des supports événementiels." },
        { kind: "media", phr: "4/5", caption: "Hors d'Œuvre · déploiement", src: "arkt/images/horsdoeuvre-5.jpg" },
        { kind: "media", phr: "4/5", caption: "Hors d'Œuvre · print", src: "arkt/images/horsdoeuvre-6.jpg" },
        { kind: "media", phr: "4/5", caption: "Hors d'Œuvre · événement", src: "arkt/images/horsdoeuvre-7.jpg" },
        { kind: "media", phr: "4/5", caption: "Hors d'Œuvre · scénographie", src: "arkt/images/horsdoeuvre-8.jpg" },
        { kind: "result", metric: "Premium", unit: "& éditorial", line: "Une marque qui s'installe d'emblée sur un registre premium et éditorial, immédiatement reconnaissable dans un univers traiteur habituellement générique. Une identité qui distingue Hors d'Œuvre dès la première impression." },
      ],
    },
    {
      id: "ciaomisu",
      story: { clarifier: "Au départ, une recette familiale de tiramisu et une ambition : ouvrir à Marseille la ==première adresse entièrement dédiée à ce dessert==. On a d'abord clarifié ce que ça devait devenir pour ne pas rester une pâtisserie de plus : **un concept lifestyle à part entière**, avec son positionnement, son nom et une promesse assez nette pour exister avant même l'ouverture.",
        piloter: "On a ensuite piloté le projet ==du concept jusqu'à l'ouverture==, en tenant ensemble la marque, le lieu et le lancement, **pour que la boutique, les contenus et la prise de parole racontent exactement la même histoire le jour J**.",
        activer: "**Et on a créé l'univers complet** : une direction artistique rétro et gourmande, une ==mascotte==, l'identité visuelle, la conception du point de vente, puis la stratégie de lancement mêlant activation digitale et ==relations presse==, avec la ligne éditoriale, les shootings et l'animation des réseaux sociaux qui l'accompagnent.",
        resultat: "**une ouverture remarquée dans le 8e**, une couverture presse immédiate (Toutma, L'Essentiel, Marseille Secrète), ==plus de 3 000 abonnés== et un concept déjà identifié comme ==la référence tiramisu de Marseille==." },
      name: "CiaoMisu!",
      year: "2026",
      tag: "Food & retail · Marseille",
      claim: "Faire naître à Marseille la première adresse entièrement dédiée au tiramisu et en faire un concept lifestyle à part entière.",
      accentName: "#E85A78",
      logo: "arkt/images/ciaomisu-logo.jpg",
      panels: [
        { kind: "intro", label: "Coup de cœur", title: "CIAOMISU! – 2026", sub: "Food & retail – Marseille" },
        { kind: "text", head: "Contexte", body: "Une recette familiale de tiramisu, une ambition claire : faire naître à Marseille la première adresse entièrement dédiée à ce dessert et en faire un concept lifestyle à part entière." },
        { kind: "media", phr: "4/5", caption: "Devanture Ciaomisu!", src: "arkt/images/ciaomisu-1.jpg" },
        { kind: "text", head: "Ce qu'on a fait", body: "Construction complète du projet, du concept à l'ouverture. Plateforme de marque et positionnement, naming, direction artistique rétro et gourmande, mascotte et identité visuelle, conception du point de vente, stratégie de lancement mêlant activation digitale, influence et presse." },
        { kind: "media", phr: "4/5", caption: "Mascotte Ciaomisu!", src: "arkt/images/ciaomisu-2.jpg" },
        { kind: "media", phr: "4/5", caption: "Intérieur Ciaomisu!", src: "arkt/images/ciaomisu-3.jpg" },
        { kind: "result", metric: "+3K", unit: "abonnés", line: "Une ouverture remarquée dans le 8e, une couverture presse immédiate (Toutma, L'Essentiel, Marseille Secrète), et un concept déjà identifié comme la référence tiramisu de Marseille." },
      ],
    },
    {
      id: "meulerie",
      story: { clarifier: "La Meulerie, c'est **ARKT dans le rôle du fondateur**. Le point de départ : rendre le bon fromage accessible et désirable, sur un marché perçu comme traditionnel et figé. On a d'abord clarifié ce que serait la marque, à contre-courant de la fromagerie classique : un concept fédérateur autour de la ==joie de vivre==, du partage et de la simplicité, porté par l'énergie de Marseille.",
        piloter: "On a ensuite piloté le développement comme on le fait pour nos clients, mais avec nos propres enjeux : ouvrir, tenir la cohérence entre chaque boutique, **faire grandir la communauté sans diluer l'esprit** et décider à chaque étape de ce qui mérite d'être lancé ou non.",
        activer: "Et on a créé l'univers de la marque : une identité forte et colorée, un ton inclusif où tout le monde se sent bien, une communication digitale affirmée et le déploiement retail des points de vente, avec les contenus, les shootings et l'animation des réseaux sociaux qui font vivre la communauté au quotidien. **Une marque assez désirable pour que de grands noms viennent collaborer avec elle** : ==Asics, American Vintage, Gertrude, Foot Locker== ou les Spartiates, l'équipe de hockey de Marseille.",
        resultat: "**==4 boutiques== lancées à Marseille en moins de 3 ans**, une franchise en cours et un rayonnement qui dépasse largement les points de vente grâce à la communauté." },
      name: "La Meulerie",
      year: "2021",
      tag: "Cofondé par ARKT",
      claim: "La preuve qu'ARKT ne fait pas que conseiller : le cabinet construit.",
      accentName: "#F2B705",
      logo: "arkt/images/meulerie-logo.jpg",
      panels: [
        { kind: "intro", label: "Coup de cœur", title: "La Meulerie", sub: "Le bon fromage, rendu désirable. Porté par l'énergie de Marseille." },
        { kind: "video", src: "arkt/videos/meulerie-1.mp4", poster: "arkt/videos/meulerie-1.jpg" },
        { kind: "video", src: "arkt/videos/meulerie-2.mp4", poster: "arkt/videos/meulerie-2.jpg" },
        { kind: "text", head: "Contexte", body: "Rendre le bon fromage accessible et désirable, sur un marché (la fromagerie) perçu comme traditionnel et figé. Tout réinventer : le ton, le lieu, la communauté." },
        { kind: "media", phr: "16/10", caption: "Duo fondateurs · scooter jaune", src: "arkt/images/meulerie-1.jpg" },
        { kind: "text", head: "Ce qu'on a fait", body: "Une marque forte et un univers coloré, inclusif, où tout le monde se sent bien. Un concept fédérateur : joie de vivre, partage, simplicité. Une communauté engagée, une communication digitale affirmée, des partenariats audacieux, un déploiement retail." },
        { kind: "media", phr: "3/4", caption: "Devanture jaune « FROMAGERIE »", src: "arkt/images/meulerie-2.jpg" },
        { kind: "media", phr: "3/4", caption: "Néon « Say Cheese »", src: "arkt/images/meulerie-3.jpg" },
        { kind: "result", metric: "4", unit: "boutiques", line: "Lancées à Marseille en moins de 3 ans. Franchise en cours, et un rayonnement bien au-delà des points de vente grâce à la communauté." },
      ],
    },
    {
      id: "airbnb",
      offres: ["Clarifier", "Activer"],
      story: { clarifier: "Airbnb voulait faire exister ses Experiences parisiennes là où l'attention se joue aujourd'hui : dans la vidéo courte, un format où tout le monde publie et où presque rien ne retient. **On a d'abord clarifié l'enjeu : ne pas montrer des activités mais provoquer de la ==projection==**, ce moment où l'on se voit soi-même en train de vivre l'expérience. On a analysé les codes qui fonctionnent réellement sur ces formats et défini une stratégie de contenu et d'acquisition construite autour d'eux.",
        activer: "**On a créé les concepts éditoriaux qui la portent** : des mécaniques vidéo courtes pensées pour transformer ==l'attention en désir==, avec la direction artistique et les contenus qui les incarnent.",
        resultat: "une mécanique éditoriale conçue pour la performance vidéo courte, capable de transformer **une seconde d'attention en ==envie de réserver==**. Les métriques de campagne sont à venir." },
      name: "Airbnb",
      year: "2026",
      tag: "Airbnb Experiences · Paris",
      claim: "Quand une marque mondiale confie à ARKT la projection de ses utilisateurs.",
      accentName: "#FF385C",
      logo: "arkt/images/airbnb-logo.jpg",
      panels: [
        { kind: "intro", label: "Coup de cœur", title: "Airbnb", sub: "Faire émerger le désir autour des Airbnb Experiences à Paris." },
        { kind: "text", head: "Contexte", body: "Faire naître le désir et la projection chez les utilisateurs autour des Airbnb Experiences à Paris, dans un environnement dominé par le format vidéo court." },
        { kind: "media", phr: "9/16", caption: "Airbnb Experiences · marque", src: "arkt/images/airbnb-1.jpg" },
        { kind: "text", head: "Ce qu'on a fait", body: "Définition d'une stratégie de contenu et d'acquisition centrée sur les formats vidéo courts. Analyse des codes performants. Création de concepts éditoriaux capables de générer du désir et de la projection." },
        { kind: "media", phr: "9/16", caption: "App host · vue programme", src: "arkt/images/airbnb-2.jpg" },
        { kind: "media", phr: "9/16", caption: "Expérience · The French Bastards", src: "arkt/images/airbnb-3.jpg" },
        { kind: "result", metric: "Désir", unit: "& projection", line: "Une mécanique éditoriale pensée pour la performance vidéo courte, conçue pour transformer l'attention en projection. Métriques de campagne à venir." },
      ],
    },
  ],

  /* ---------- projets épinglés : ouverts en permanence dans "Tous les projets",
     dans cet ordre, séparés par deux rangées de vignettes ---------- */
  pinned: ["airbnb", "meulerie", "pernodricard", "palauma"],

  /* ---------- grille (déploiement au clic) ---------- */
  grid: [
    { id: "nb1", name: "NB1", year: "2026", phr: "4/5", short: "Vidéos produit · campagne ads",
      offres: ["Activer"],
      story: { activer: "NB1 lançait des campagnes ads et avait besoin de **vidéos qui vendent, pas de belles images** : des formats courts, pensés pour la publicité sur les réseaux sociaux, où le produit est ==compris en trois secondes==. ==On a créé les contenus de A à Z== : direction artistique, tournages produit avec des visages qui incarnent la marque, montage en formats publicitaires prêts à diffuser dans les campagnes ads.",
        resultat: "une série de vidéos produit **taillées pour la performance publicitaire**, cohérentes entre elles et ==directement exploitables en ads==, que l'on peut voir ici même." },
      logo: "arkt/images/nb1-logo.jpg",
      photos: [
        { video: "arkt/videos/nb1-driss.mp4", poster: "arkt/videos/nb1-driss.jpg" },
        { video: "arkt/videos/nb1-suzane.mp4", poster: "arkt/videos/nb1-suzane.jpg" },
        { video: "arkt/videos/nb1-karine.mp4", poster: "arkt/videos/nb1-karine.jpg" },
        { video: "arkt/videos/nb1-jo-1.mp4" },
        { video: "arkt/videos/nb1-jo-4.mp4" },
        { video: "arkt/videos/nb1-suzane-1.mp4" },
        { video: "arkt/videos/nb1-karine-3.mp4" },
      ],
      tags: ["Production vidéo", "Contenu ads", "Acquisition", "Communication"],
      body: "Des vidéos produit pensées pour convertir, au service d'une campagne d'acquisition." },
    { id: "palauma", name: "Palauma", year: "2026", phr: "4/5", short: "Outsider d'un immobilier standardisé",
      story: { clarifier: "Palauma Global Group évolue sur un marché immobilier où tout le monde dit la même chose de la même façon. On a d'abord clarifié ce qui le distingue vraiment et comment le dire : **une posture assumée d'==outsider==**, un storytelling qui raconte la façon dont le groupe travaille plutôt que ce qu'il vend et ==des messages qui tiennent face à des concurrents plus gros==.",
        piloter: "On a ensuite piloté la prise de parole dans la durée : quels sujets porter, sur quel ton, à quel rythme et ==ce qu'il vaut mieux ne pas dire==, **pour que chaque publication renforce la même image plutôt que de la diluer**.",
        activer: "Et on a créé **la stratégie éditoriale LinkedIn du groupe et de ses dirigeants**, les contenus qui la portent, la direction artistique et les shootings qui donnent un visage à la marque et l'animation des réseaux sociaux qui installe Palauma comme ==une voix reconnaissable== dans son secteur.",
        resultat: "==une marque que l'on connaît désormais==, ==une confiance== qui s'est installée auprès des partenaires comme des clients et **des projets qui s'enchaînent**. Palauma n'est plus interchangeable et son discours, les équipes peuvent le tenir partout, de la même façon." },
      logo: "arkt/images/palauma-logo.jpg",
      photos: ["arkt/images/palauma-1.jpg", "arkt/images/palauma-2.jpg", "arkt/images/palauma-3.jpg", "arkt/images/palauma-4.jpg", "arkt/images/palauma-5.jpg"],
      tags: ["Positionnement", "Storytelling", "Éditorial LinkedIn"],
      body: "Donner à un groupe immobilier une voix d'outsider sur un marché standardisé." },
    { id: "crousty", name: "Crousty Crew", year: "2026", phr: "4/5", short: "Pour Taster · street food",
      offres: ["Activer"],
      story: { activer: "Taster voulait lancer Crousty Crew, une marque de street food qui devait exister tout de suite, avec une personnalité assez forte pour tenir en cuisine comme en devanture. **On a créé la marque de bout en bout** : la plateforme de marque et le positionnement, une identité qui emprunte aux ==codes de la brigade et du streetwear==, la direction artistique et les codes architecturaux et retail qui permettent de la déployer physiquement, ==lieu après lieu==, sans jamais la diluer.",
        resultat: "une marque street food **reconnaissable au premier coup d'œil**, cohérente de l'enseigne au packaging et pensée pour ==se dupliquer durablement==." },
      logo: "arkt/images/crousty-logo.jpg",
      photos: ["arkt/images/crousty-1.jpg", "arkt/images/crousty-2.jpg", "arkt/images/crousty-3.jpg", "arkt/images/crousty-4.jpg", "arkt/images/crousty-5.jpg", "arkt/images/crousty-6.jpg", "arkt/images/crousty-7.jpg"],
      tags: ["Plateforme de marque", "DA", "Codes retail & archi"],
      body: "Une marque street food aux codes brigade et streetwear, prête pour le retail." },
    { id: "vitamine", name: "Vitamine", year: "2026", phr: "4/5", short: "Breakfast Club · rituel d'entreprise",
      offres: ["Clarifier", "Activer"],
      story: { clarifier: "Vitamine Breakfast Club part d'une idée simple : **faire du petit-déjeuner en entreprise un vrai moment**, pas une viennoiserie posée sur une table de réunion. On a d'abord clarifié le territoire de la marque : ==un rituel collectif== qui mêle ==performance et convivialité==, un nom qui donne de l'énergie et une promesse que les entreprises comprennent en une phrase.",
        activer: "**Et on a créé la marque de bout en bout**, en veillant à ce que chaque élément, du nom au visuel jusqu'au ton, serve ce même positionnement : la plateforme de marque, le naming, l'identité visuelle et la direction artistique complète, puis la ligne éditoriale, les shootings et l'animation des réseaux sociaux qui donnent à voir ce rituel et ==donnent envie de l'adopter==.",
        resultat: "une marque qui ==se distingue immédiatement== des offres de restauration d'entreprise classiques et qui installe le petit-déjeuner comme **un moment de marque à part entière**." },
      logo: "arkt/images/vitamine-logo.jpg",
      photos: ["arkt/images/vitamine-1.jpg", "arkt/images/vitamine-2.jpg", "arkt/images/vitamine-3.jpg", "arkt/images/vitamine-4.jpg", "arkt/images/vitamine-5.jpg", "arkt/images/vitamine-6.jpg"],
      tags: ["Naming", "Plateforme de marque", "Identité visuelle", "DA"],
      body: "Faire du petit-déjeuner en entreprise un vrai rituel de marque." },
    { id: "pernodricard", name: "Pernod Ricard", year: "2026", phr: "4/5", short: "Maison Yellow · terrasse Ricard",
      offres: ["Clarifier", "Activer"],
      story: { clarifier: "Pernod Ricard voulait repenser la terrasse de Maison Yellow pour qu'elle ne soit plus un espace de consommation mais **un lieu que l'on vient vivre**. On a d'abord clarifié le territoire : ==une place de village méditerranéenne==, avec tout ce qu'elle évoque de convivialité, de lenteur et de lien, traduite dans les codes visuels de Ricard ==sans jamais tomber dans le décor de carte postale==.", activer: "**Et on a créé la terrasse elle-même** : la scénographie, l'agencement, le mobilier, la végétalisation et la mise en scène des codes Ricard, jusqu'à la production et l'installation, pour que le concept se ressente ==dès qu'on s'assoit==.", resultat: "une terrasse qui a une identité et une atmosphère, **où la marque se vit plutôt qu'elle ne s'affiche** et qui ==donne envie de rester==." },
      logo: "arkt/images/pernodricard-logo.jpg",
      photos: ["arkt/images/pernodricard-1.jpg", "arkt/images/pernodricard-2.jpg", "arkt/images/pernodricard-3.jpg", "arkt/images/pernodricard-4.jpg", "arkt/images/pernodricard-5.jpg"],
      tags: ["Scénographie", "Design d'espace", "Expérientiel"],
      body: "La terrasse de Maison Yellow transformée en place de village méditerranéenne." },
    { id: "adriensusini", name: "Adrien Susini", year: "2026", phr: "4/5", short: "Chanteur corse · site & univers",
      story: { clarifier: "Adrien Susini, chanteur corse, auteur-compositeur et interprète, avait une musique, un parcours et une histoire forte, mais **pas d'endroit où tout cela se tenait ensemble**. On a d'abord clarifié son univers artistique : ce qui le définit, ce que son ==parcours de résilience== dit de sa musique et ce qu'un programmateur, un journaliste ou un auditeur doit comprendre de lui ==en trente secondes==.",
        piloter: "On a ensuite piloté la construction de sa présence pour que le site, les contenus et la prise de parole racontent ==un seul et même artiste==, avec une hiérarchie claire : **la musique d'abord, l'histoire ensuite, le contact toujours à portée de main**.",
        activer: "**Et on a créé son site web, de la conception au développement**, sa stratégie éditoriale et son ==identité digitale==, avec la direction artistique des shootings et l'animation des réseaux sociaux qui prolongent l'univers du site au quotidien.",
        resultat: "un artiste qui a enfin **une adresse à son image**, où l'on découvre sa musique, ses dates et son histoire et depuis laquelle programmateurs et journalistes ==le contactent directement==." },
      logo: "arkt/images/adriensusini-logo.jpg",
      photos: ["arkt/images/adriensusini-1.jpg", "arkt/images/adriensusini-2.jpg", "arkt/images/adriensusini-3.jpg", "arkt/images/adriensusini-4.jpg"],
      tags: ["Site web", "Stratégie éditoriale", "Identité digitale"],
      body: "Donner à un artiste une adresse à l'image de sa musique et de son histoire." },
    { id: "estelletorossian", name: "Estelle Torossian", year: "2026", phr: "4/5", short: "Médecine esthétique · marque",
      story: { clarifier: "Le Dr Estelle Torossian, médecin esthétique à Marseille, avait l'expertise et la clientèle, mais une image qui restait celle d'un cabinet médical : sérieuse, attendue, invisible pour une génération qui ==choisit son médecin sur Instagram==. On a d'abord clarifié ce que sa marque pouvait devenir sans trahir la rigueur médicale : **une ==marque culturelle==, où la précision scientifique cohabite avec l'humour, la pop culture et la désirabilité**, pour parler à une audience plus jeune et plus connectée.",
        piloter: "On a ensuite piloté cette transformation dans la durée, en tenant ==l'équilibre== à chaque prise de parole : **assez décalé pour exister, jamais au point de fragiliser la crédibilité d'un médecin**.",
        activer: "Et on a créé la stratégie de contenu et d'image, la ligne éditoriale, **la direction artistique des shootings et l'animation des réseaux sociaux** qui ==font vivre cette marque au quotidien==.",
        resultat: "un médecin esthétique qui n'est plus « un cabinet parmi d'autres » mais **une marque avec un ton**, une audience qui s'élargit et ==une désirabilité qui précède désormais la consultation==." },
      logo: "arkt/images/estelletorossian-logo.jpg",
      photos: [{ video: "arkt/videos/estelletorossian-1.mp4", poster: "arkt/videos/estelletorossian-1.jpg" }, "arkt/images/estelletorossian-1.jpg", "arkt/images/estelletorossian-2.jpg", "arkt/images/estelletorossian-3.jpg", "arkt/images/estelletorossian-4.jpg", "arkt/images/estelletorossian-5.jpg"],
      tags: ["Stratégie de contenu", "Image de marque", "Éditorial"],
      body: "Du cabinet médical à la marque culturelle." },
    { id: "egoz", name: "Egoz", year: "2026", phr: "4/5", short: "Marque · stratégie & identité",
      story: { clarifier: "Egoz, c'est une boisson au ==lait de macadamia==, avec **un produit qui a tout pour lui mais une marque qui ne lui rendait pas justice**. On a d'abord clarifié son positionnement : ce qu'Egoz a d'unique face aux autres laits végétaux, à qui elle s'adresse en priorité et ce qu'elle doit dire pour ==donner envie avant même d'expliquer==.",
        piloter: "On a ensuite piloté le repositionnement dans la durée, en reprenant la stratégie et la communication de la marque : choisir les sujets, ==tenir le cap== d'une prise de parole à l'autre et accompagner le développement de la distribution **pour que l'image et la présence en rayon avancent ensemble**.",
        activer: "Et on a créé la ==nouvelle ligne éditoriale==, la direction artistique des shootings et l'animation des réseaux sociaux qui donnent à la marque **le visage qu'elle méritait**.",
        resultat: "une marque qui trouve peu à peu son public, **une communauté Instagram qui grandit** et une brique qui s'installe dans ==de nouveaux points de vente==. Un repositionnement qui se construit dans le temps et dont ==chaque nouvelle référence est une étape==." },
      logo: "arkt/images/egoz-logo.jpg",
      photos: ["arkt/images/egoz-1.jpg", "arkt/images/egoz-2.jpg", "arkt/images/egoz-3.jpg", "arkt/images/egoz-4.jpg", "arkt/images/egoz-5.jpg"],
      tags: ["Stratégie de marque", "Identité visuelle"],
      body: "Redonner à une boisson au lait de macadamia la marque qu'elle mérite." },
    { id: "caparle", name: "Ça Parle", year: "2026", phr: "4/5", short: "Communication · stratégie éditoriale",
      story: { clarifier: "Ça Parle est la marque sœur d'Hors d'Œuvre : une agence événementielle qui fait s'exprimer les talents de Marseille, ici et ailleurs, pour ==mettre la ville sur le devant de la scène==. Au départ, une intuition et une énergie, mais pas encore de marque. On a d'abord clarifié ce qu'elle devait être : **une voix marseillaise, fière et généreuse**, qui ne se contente pas d'organiser des événements mais qui ==donne une scène à ceux qui font la ville==, avec un nom qui dit exactement ça.",
        piloter: "On a ensuite piloté la marque **de sa création jusqu'à aujourd'hui et on s'en occupe encore** : choisir les projets qui servent le propos, qu'il s'agisse de ==lancements de marque==, de soirées ou d'événements sur mesure, tenir le lien avec Hors d'Œuvre sans confondre les deux et faire grandir Ça Parle événement après événement, en gardant la même ligne.",
        activer: "**Et on a créé l'ensemble de A à Z** : le nom, l'identité visuelle, le site, la stratégie éditoriale et la communication de chaque événement, avec les contenus, la direction artistique des shootings et l'animation des réseaux sociaux qui prolongent chaque événement ==bien au-delà du jour J==.",
        resultat: "une marque événementielle identifiée à Marseille et au-delà, **une scène pour les talents de la ville** et un projet qui ==continue de grandir avec nous==." },
      logo: "arkt/images/caparle-logo.jpg",
      photos: [{ video: "arkt/videos/caparle-1.mp4", poster: "arkt/videos/caparle-1.jpg" }, { video: "arkt/videos/caparle-2.mp4", poster: "arkt/videos/caparle-2.jpg" }, "arkt/images/caparle-1.jpg", "arkt/images/caparle-2.jpg", "arkt/images/caparle-3.jpg", "arkt/images/caparle-4.jpg", "arkt/images/caparle-5.jpg"],
      tags: ["Stratégie éditoriale", "Communication"],
      body: "Donner une scène aux talents de Marseille, ici et ailleurs." },
    { id: "capsule", name: "Capsule", year: "2025", phr: "4/5", short: "Salle de Pilates Reformer · Marseille",
      offres: ["Clarifier", "Activer"],
      story: { clarifier: "Une salle de Pilates Reformer qui ouvre à Marseille, sur un créneau où les studios se multiplient et se ressemblent. On a d'abord clarifié ce que Capsule devait être : **pas une salle de sport de plus mais ==un club==**, avec un positionnement net, un nom qui évoque un lieu à part et une promesse que l'on comprend ==avant même de pousser la porte==.",
        activer: "**Et on a créé tout ce qu'il fallait pour ouvrir** : le naming, la charte visuelle et la direction artistique, le site web, la stratégie de contenu et de lancement digital, avec les shootings et l'animation des réseaux sociaux qui ont fait exister Capsule ==avant le premier cours==.",
        resultat: "un club identifié ==dès l'ouverture==, avec **une marque complète et cohérente, du nom jusqu'au site**, prête à accueillir ses premiers membres." },
      logo: "arkt/images/capsule-logo.jpg",
      photos: ["arkt/images/capsule-1.jpg", "arkt/images/capsule-2.jpg", "arkt/images/capsule-3.jpg", "arkt/images/capsule-4.jpg", "arkt/images/capsule-5.jpg"],
      tags: ["Naming", "Identité & DA", "Site web", "Positionnement", "Contenu & lancement"],
      body: "Lancer une salle de Pilates Reformer avec une marque complète, du nom au site." },
    { id: "kube", name: "Kube", year: "2025", phr: "4/5", short: "Bootcamp · Marseille",
      offres: ["Piloter", "Activer"],
      story: { piloter: "Kube, c'est un bootcamp nouvelle génération à Marseille, avec une équipe qui produit beaucoup de contenus mais ==sans cap pour les tenir ensemble==. ==On a piloté la marque dans la durée== : définir le persona et le positionnement, arbitrer ce qui se dit et ce qui ne se dit pas, valider les contenus et superviser leur production **pour que tout ce qui sort ressemble à Kube et à personne d'autre**.", activer: "Et on a créé ce qui manquait pour que ce pilotage tienne : la charte de marque, l'identité visuelle, le ==ton of voice== et la stratégie réseaux sociaux qui donnent à l'équipe **un cadre clair pour produire seule**.", resultat: "une marque de bootcamp ==identifiable sur les réseaux==, une équipe qui produit avec un cadre et **une présence sociale cohérente semaine après semaine**." },
      logo: "arkt/images/kube-logo.jpg",
      photos: [{ video: "arkt/videos/kube-1.mp4", poster: "arkt/videos/kube-1.jpg" }, "arkt/images/kube-1.jpg", "arkt/images/kube-2.jpg", "arkt/images/kube-3.jpg", "arkt/images/kube-4.jpg", "arkt/images/kube-5.jpg", "arkt/images/kube-6.jpg"],
      tags: ["Charte de marque", "Identité & ton", "Persona", "Stratégie social"],
      body: "Donner à un bootcamp nouvelle génération une marque, un ton et une présence sociale." },
    { id: "pattaxnike", name: "Patta × Nike", year: "2025", phr: "4/5", short: "Pop-up instore · scénographie",
      offres: ["Activer"],
      story: { activer: "Pour le pop-up Nike × Patta chez SAISON, il fallait **qu'un magasin devienne, le temps d'un lancement, un moment de marque** : que l'esprit ==« Get Familiar »== de la collaboration se ressente dès l'entrée, sans se contenter de poser les produits sur des étagères. ==On a créé la scénographie instore de A à Z== : concept, set design, volumes et matières, jusqu'à la production et l'installation sur place, pour transformer l'espace en une expérience à la hauteur de deux marques qui ne laissent rien au hasard.",
        resultat: "**un pop-up vivant**, fidèle à l'univers de la collaboration, qui a fait du magasin un lieu où l'on vient ==pour l'expérience autant que pour le produit==." },
      logo: "arkt/images/pattaxnike-logo.jpg",
      photos: ["arkt/images/pattaxnike-1.jpg", "arkt/images/pattaxnike-2.jpg", "arkt/images/pattaxnike-3.jpg", "arkt/images/pattaxnike-4.jpg", "arkt/images/pattaxnike-5.jpg"],
      tags: ["Scénographie", "Set design", "Activation marque"],
      body: "Traduire l'esprit « Get Familiar » en scénographie instore chez SAISON." },
    { id: "nike", name: "Nike", year: "2025", phr: "4/5", short: "Total 90 · événement & set design",
      offres: ["Activer"],
      story: { activer: "Nike rééditait la ==Total 90==, un modèle iconique, en exclusivité chez Saison à Marseille et voulait **que ce lancement se vive localement plutôt qu'il ne s'annonce**. On a créé l'événement d'influence et le set design qui l'accompagnait : un dispositif pensé pour la scène marseillaise, avec ==les bonnes personnes dans la salle==, une mise en scène du produit à la hauteur de son statut et de quoi faire circuler le moment bien au-delà du magasin.",
        resultat: "un lancement qui **a existé à Marseille comme un vrai événement**, une Total 90 mise en valeur comme la pièce qu'elle est et une soirée ==relayée par ceux qui comptent localement==." },
      logo: "arkt/images/nike-logo.jpg",
      photos: ["arkt/images/nike-1.jpg", "arkt/images/nike-2.jpg", "arkt/images/nike-3.jpg", "arkt/images/nike-4.jpg"],
      tags: ["Événement", "Set design", "Influence locale"],
      body: "Un événement d'influence et un set design pour la réédition de la Total 90." },
    { id: "placedesfinances", name: "Place des Finances", year: "2025", phr: "4/5", short: "Insuretech · Marseille",
      offres: ["Clarifier"],
      story: { clarifier: "Place des Finances est une insuretech marseillaise qui s'adressait à la fois aux particuliers et aux entreprises, avec une marque et un discours qui ==ne faisaient plus la différence entre les deux==. ==On a clarifié l'ensemble== : ce que la marque devait incarner, comment elle devait se présenter et, surtout, **une stratégie de déploiement commercial distincte pour le BtoC et le BtoB**, avec des cibles, des messages et des priorités propres à chacun.", resultat: "une marque repositionnée, **deux stratégies commerciales nettes au lieu d'une seule floue** et ==une direction claire== pour piloter le rebranding et le déploiement qui ont suivi." },
      logo: "arkt/images/placedesfinances-logo.jpg",
      photos: ["arkt/images/placedesfinances-1.jpg", "arkt/images/placedesfinances-2.jpg", "arkt/images/placedesfinances-3.jpg", "arkt/images/placedesfinances-4.jpg", "arkt/images/placedesfinances-5.jpg"],
      tags: ["Rebranding", "Stratégie BtoC & BtoB"],
      body: "Une marque et deux stratégies commerciales, BtoC et BtoB." },
    { id: "spilow", name: "Spilow", year: "2025", phr: "4/5", short: "Pilates Club · Aubagne",
      offres: ["Clarifier", "Activer"],
      story: { clarifier: "Spilow, c'est un Pilates Club qui ouvre à Aubagne, avec une question de départ : comment exister avec sa propre personnalité quand la référence, à quelques kilomètres, ==s'appelle Marseille==. On a d'abord clarifié le positionnement : **un club de proximité, chaleureux et exigeant à la fois**, avec un nom court et sympathique qui se retient tout de suite et une promesse tournée vers ==les gens du coin==.",
        activer: "**Et on a créé ce qu'il fallait pour lancer** : le naming, la charte visuelle, la stratégie de positionnement et la communication de lancement, avec les contenus et l'animation des réseaux sociaux qui ont fait connaître le club ==avant même son ouverture==.",
        resultat: "**un club qui a son identité propre**, identifié à Aubagne dès le lancement, avec une marque ==prête à grandir==." },
      logo: "arkt/images/spilow-logo.jpg",
      photos: ["arkt/images/spilow-1.jpg", "arkt/images/spilow-2.jpg", "arkt/images/spilow-3.jpg", "arkt/images/spilow-4.jpg", "arkt/images/spilow-5.jpg"],
      tags: ["Naming", "Charte visuelle", "Positionnement", "Communication"],
      body: "Nom, identité et lancement d'un Pilates Club à Aubagne." },
    { id: "lademeure", name: "La Demeure", year: "2025", phr: "4/5", short: "Boutique · rebranding suite à reprise",
      offres: ["Clarifier", "Activer"],
      story: { clarifier: "Une boutique reprise en novembre 2024 par de nouveaux propriétaires, avec ==une enseigne qui ne leur ressemblait pas== et une offre à faire évoluer. On a d'abord clarifié ce que le lieu devait devenir entre leurs mains : un positionnement repensé, une offre recentrée et **un nouveau nom, La Demeure**, qui installe d'emblée une idée de ==maison, d'accueil et de choses choisies avec soin==.",
        activer: "Et on a créé la ==nouvelle identité== de la boutique : le naming, l'identité visuelle et ses déclinaisons sur le lieu et les supports, **pour que la reprise se voie et se ressente dès la façade**.",
        resultat: "une boutique qui a **changé de mains et d'époque en même temps**, avec une marque à l'image de ses nouveaux propriétaires et ==une offre lisible== pour ses clients." },
      logo: "arkt/images/lademeure-logo.jpg",
      photos: ["arkt/images/lademeure-1.jpg", "arkt/images/lademeure-2.jpg", "arkt/images/lademeure-3.jpg", "arkt/images/lademeure-4.jpg", "arkt/images/lademeure-5.jpg", "arkt/images/lademeure-6.jpg"],
      tags: ["Rebranding", "Identité visuelle"],
      body: "Nouveau nom, nouvelle identité et offre repositionnée après la reprise de la boutique." },
    { id: "puma", name: "Puma", year: "2025", phr: "4/5", short: "Set design retail · activation produit",
      offres: ["Activer"],
      story: { activer: "Puma avait des produits à mettre en avant en point de vente et un enjeu simple : **qu'on les voie, qu'on s'arrête et qu'on ait envie de les toucher**. On a créé le set design : le concept de mise en scène, avec ==le produit en héros== et un univers fidèle aux codes de la marque, puis la scénographie, les volumes et les matières qui l'installent dans le magasin comme ==un objet de désir== plutôt que comme une référence en rayon.",
        resultat: "une présence produit qui **se remarque dès l'entrée du point de vente** et une activation ==cohérente avec l'univers Puma==." },
      logo: "arkt/images/puma-logo.jpg",
      photos: ["arkt/images/puma-1.jpg", "arkt/images/puma-2.jpg", "arkt/images/puma-3.jpg", "arkt/images/puma-4.jpg", "arkt/images/puma-5.jpg"],
      tags: ["Set design", "Retail", "Activation marque"],
      body: "Un set design pour mettre les produits Puma en scène en point de vente." },
    { id: "ve", name: "Vé", year: "2024", phr: "4/5", short: "Glacier végétal · Marseille",
      story: { clarifier: "Un glacier ==100 % végétal== à Marseille, avec une conviction forte sur le produit et une idée très nette de ce que le fondateur ne voulait surtout pas. On a d'abord clarifié ce que Vé devait être : **pas un glacier « alternatif » qui s'excuse d'être végétal, mais un glacier marseillais désirable pour tout le monde**, avec un nom court, populaire et local qui claque comme ==une expression du coin==.",
        piloter: "On a ensuite piloté le lancement pour que le nom, le lieu, le visuel et la prise de parole **arrivent ensemble et cohérents**, sans qu'aucun élément ne renvoie l'image d'une adresse ==militante ou confidentielle==.",
        activer: "Et on a créé le ==naming, la charte visuelle==, la stratégie de positionnement et la communication de lancement, avec les contenus, les shootings et l'animation des réseaux sociaux qui ont **installé Vé dans le paysage marseillais**.",
        resultat: "une adresse ==identifiée dès l'ouverture== et un glacier dont on parle d'abord **pour sa beauté et son goût, pas pour son étiquette végétale**." },
      logo: "arkt/images/ve-logo.jpg",
      photos: ["arkt/images/ve-1.jpg", "arkt/images/ve-2.jpg", "arkt/images/ve-3.jpg", "arkt/images/ve-4.jpg", "arkt/images/ve-5.jpg", "arkt/images/ve-6.jpg"],
      tags: ["Naming", "Charte visuelle", "Positionnement", "Communication"],
      body: "Un glacier végétal qu'on choisit pour sa beauté et son goût, pas pour son étiquette." },
    { id: "nailledit", name: "Nailed It", year: "2024", phr: "4/5", short: "Événementiel · naming & branding",
      story: { clarifier: "Une agence d'événementiel d'entreprise qui se lance sur un marché encombré, où les agences se ressemblent et se vendent toutes sur la « créativité ». On a d'abord clarifié l'angle : **une agence qui promet d'abord l'exécution parfaite**, celle qui ==« cloue » l'événement==, avec un nom qui dit exactement ça et un positionnement qui ==rassure les directions d'entreprise== avant même de les séduire.",
        piloter: "On a ensuite piloté le lancement de la marque pour que le nom, l'identité et les premières prises de parole installent d'emblée **cette promesse de fiabilité**, ==sans tomber dans le corporate froid==.",
        activer: "Et on a créé le ==naming, la charte visuelle==, la stratégie de positionnement et la communication de lancement, avec les contenus et l'animation des réseaux sociaux qui donnent à l'agence **une présence à la hauteur de ce qu'elle organise**.",
        resultat: "une agence qui arrive sur le marché avec **un nom qu'on retient, une promesse claire** et une image qui ==la sort tout de suite du lot== des agences interchangeables." },
      logo: "arkt/images/nailledit-logo.jpg",
      photos: ["arkt/images/nailledit-1.jpg", "arkt/images/nailledit-2.jpg", "arkt/images/nailledit-3.jpg", "arkt/images/nailledit-4.jpg"],
      tags: ["Naming", "Charte visuelle", "Positionnement", "Communication"],
      body: "Une agence événementielle qui promet d'abord l'exécution parfaite." },
    { id: "apt20", name: "APT 20", year: "2024", phr: "4/5", short: "Coffee shop · design d'espace",
      offres: ["Activer"],
      story: { activer: "APT 20, c'est un coffee shop à Marseille, avec un espace à concevoir pour qu'il soit à la fois **un lieu où l'on s'attarde et un outil de travail efficace pour l'équipe**. ==On a créé le design d'espace== : l'agencement, la circulation entre le comptoir et la salle, les matières et l'ambiance qui donnent envie de rester, avec l'accompagnement des travaux ==jusqu'à l'ouverture==.",
        resultat: "un coffee shop qui a **une atmosphère à lui**, où ==l'espace fait partie de l'expérience== autant que le café." },
      logo: "arkt/images/apt20-logo.jpg",
      photos: ["arkt/images/apt20-1.jpg", "arkt/images/apt20-2.jpg", "arkt/images/apt20-3.jpg", "arkt/images/apt20-4.jpg", "arkt/images/apt20-5.jpg", "arkt/images/apt20-6.jpg"],
      tags: ["Design d'espace"],
      body: "Le design d'espace d'un coffee shop marseillais." },
    { id: "richelieu", name: "Richelieu", year: "2024", phr: "4/5", short: "Chaussures · design d'espace",
      offres: ["Activer"],
      story: { activer: "Richelieu est une boutique de chaussures et d'accessoires haut de gamme à Marseille, **dont l'espace ne racontait plus le niveau de ce qu'elle vend**. On a créé, via Bart & Pucci, le design d'espace et la stratégie de merchandising : un agencement qui met ==chaque paire en valeur comme une pièce==, des matières et une lumière à la hauteur des produits et une logique de présentation qui guide le client et ==facilite le travail des vendeurs==.",
        resultat: "une boutique dont l'espace est **enfin au niveau de sa sélection**, où le produit ==se voit, se comprend et se vend mieux==." },
      logo: "arkt/images/richelieu-logo.jpg",
      photos: ["arkt/images/richelieu-1.jpg", "arkt/images/richelieu-2.jpg", "arkt/images/richelieu-3.jpg", "arkt/images/richelieu-4.jpg", "arkt/images/richelieu-5.jpg", "arkt/images/richelieu-6.jpg", "arkt/images/richelieu-7.jpg", "arkt/images/richelieu-8.jpg"],
      tags: ["Design d'espace", "Merchandising", "Via Bart & Pucci"],
      body: "Design d'espace et merchandising pour une boutique de chaussures haut de gamme." },
    { id: "twicy", name: "Twicy", year: "2024", phr: "4/5", short: "IT reconditionnée · stratégie & media",
      story: { clarifier: "Twicy vend de l'IT reconditionnée aux entreprises, sur un marché où le sujet est encore perçu comme technique et où la confiance se gagne d'abord sur les personnes. On a d'abord clarifié deux choses : la place que le dirigeant devait prendre dans le discours, en **faisant de son personal branding la porte d'entrée vers la marque** et le territoire que Twicy pouvait s'approprier, celui du ==numérique responsable==, ==plutôt que de se battre sur le prix du matériel==.",
        piloter: "On a ensuite piloté l'ensemble de la communication dans la durée, **en direction marketing externalisée** : arbitrer les sujets, tenir la cohérence entre la parole du dirigeant et celle de la marque et intégrer suffisamment le business pour produire des contenus qui ==parlent vraiment aux clients de Twicy==.",
        activer: "Et on a créé la stratégie de communication institutionnelle, le personal branding du dirigeant, les contenus, les shootings et l'animation des réseaux sociaux, ainsi qu'**un média à part entière, ==The Big Reboot==**, dédié aux experts du numérique responsable, qui positionne Twicy comme ==une référence de son secteur== et pas seulement comme un fournisseur.",
        resultat: "une marque et un dirigeant identifiés sur leur sujet, ==un média qui fédère les experts du secteur== et un partenariat que Twicy décrit comme **un levier clé de sa croissance**." },
      logo: "arkt/images/twicy-logo.jpg",
      photos: ["arkt/images/twicy-1.jpg", "arkt/images/twicy-2.jpg", "arkt/images/twicy-3.jpg", "arkt/images/twicy-4.jpg"],
      tags: ["Personal branding", "Communication", "Média", "Accompagnement continu"],
      body: "Faire de l'IT reconditionnée un sujet de référence, porté par son dirigeant." },
    { id: "adsdesign", name: "ADS Design", year: "2024", phr: "4/5", short: "Design urbain · stratégie & marketing",
      story: { clarifier: "ADS Design conçoit du mobilier et du design urbain, avec une équipe marketing en interne mais **sans direction claire pour la faire avancer dans le même sens**. On a d'abord clarifié la stratégie de communication de l'entreprise : ==à qui elle s'adresse==, ce qu'elle doit dire aux collectivités et aux prescripteurs et sur quels sujets elle est ==légitime à prendre la parole==.",
        piloter: "On a ensuite piloté l'équipe marketing interne au quotidien, en ==management opérationnel==, tout en accompagnant les dirigeants par du ==coaching== : donner un cap à l'équipe, arbitrer les priorités, valider les actions et **faire monter tout le monde en compétence plutôt que de faire à leur place**.",
        activer: "Et on a créé ce qui manquait pour que cette organisation tienne : **un écosystème tech dédié à l'acquisition et au suivi de la relation client**, avec la mise en place d'un ==CRM==, une ==newsletter== pour entretenir le lien avec les prospects et les clients, ainsi que les contenus et l'animation des réseaux sociaux portés par l'équipe sous notre direction.",
        resultat: "**une équipe marketing qui sait où elle va et qui produit**, des dirigeants plus à l'aise avec ces sujets, une relation client suivie dans le temps et une acquisition enfin ==outillée et mesurable==." },
      logo: "arkt/images/adsdesign-logo.jpg",
      photos: ["arkt/images/adsdesign-1.jpg", "arkt/images/adsdesign-2.jpg", "arkt/images/adsdesign-3.jpg", "arkt/images/adsdesign-4.jpg", "arkt/images/adsdesign-5.jpg"],
      tags: ["Stratégie de communication", "Marketing opérationnel", "Accompagnement continu"],
      body: "Donner un cap à une équipe marketing et outiller son acquisition." },
    { id: "linstantcryo", name: "L'Instant Cryo", year: "2024", phr: "4/5", short: "Cryo & minceur · franchise",
      story: { clarifier: "L'Instant Cryo est un institut de cryothérapie et de minceur qui passait d'une adresse à un ==réseau de franchises==, avec tout ce que ça change : **un concept qui doit se dupliquer sans se dégrader** et des franchisés à faire réussir. On a d'abord clarifié ce qui faisait la valeur de la marque et ce qui devait rester identique d'un institut à l'autre, pour que le développement repose sur ==un modèle net== plutôt que sur l'énergie de la fondatrice.",
        piloter: "On a ensuite piloté ce développement dans la durée, en ==conseil stratégique récurrent== : les choix d'ouverture, la gestion opérationnelle des points de vente, les arbitrages du quotidien, avec une collaboration régulière qui a permis de **décider vite et bien à chaque étape**.",
        activer: "Et on a créé la stratégie de communication pour le lancement de la gamme de ==produits dérivés==, qui **prolonge l'expérience de l'institut jusque chez le client**, avec les contenus et l'animation des réseaux sociaux qui l'accompagnent.",
        resultat: "une chaîne qui grandit sur des bases claires, **des points de vente pilotés plutôt que subis** et une marque qui existe désormais ==au-delà des murs de ses instituts==." },
      logo: "arkt/images/linstantcryo-logo.jpg",
      photos: ["arkt/images/linstantcryo-1.jpg", "arkt/images/linstantcryo-2.jpg", "arkt/images/linstantcryo-3.jpg"],
      tags: ["Conseil stratégique", "Franchise", "Communication"],
      body: "Accompagner le passage d'un institut à un réseau de franchises." },
    { id: "accesud", name: "Accesud", year: "2024", phr: "4/5", short: "Intérim · développement commercial",
      offres: ["Clarifier", "Piloter"],
      story: { clarifier: "Accesud est une agence d'intérim marseillaise, sur un marché où les agences se ressemblent et où les clients choisissent souvent par habitude. On a d'abord clarifié ce qui pouvait la distinguer : sa ==proximité==, sa réactivité et une façon de travailler ==plus humaine== que les grands réseaux, pour en faire **un vrai argument commercial plutôt qu'un simple état de fait**.", piloter: "On a ensuite piloté le développement commercial dans la durée : **prioriser les cibles, structurer la prospection**, arbitrer où mettre l'énergie de l'équipe et accompagner la refonte de l'image de l'agence pour qu'elle soit ==à la hauteur de ce nouveau discours==.", resultat: "une agence qui **sait ce qui la rend différente et qui le dit**, ==une prospection organisée== et une image enfin alignée sur la qualité de son service." },
      logo: "arkt/images/accesud-logo.jpg",
      photos: ["arkt/images/accesud-1.jpg", "arkt/images/accesud-2.jpg", "arkt/images/accesud-3.jpg"],
      tags: ["Conseil stratégique", "Développement commercial", "Branding"],
      body: "Faire de la proximité d'une agence d'intérim un vrai argument commercial." },
    { id: "marymadeleine", name: "Mary Madeleine", year: "2023", phr: "4/5", short: "Madeleines · naming & branding",
      story: { clarifier: "Une chaîne de magasins dédiés à la madeleine, à Marseille : un produit que tout le monde connaît, qu'il fallait rendre désirable et ==digne d'une enseigne à part entière==. On a d'abord clarifié le positionnement : **une marque gourmande et affective**, qui joue sur la mémoire et le plaisir simple sans tomber dans la nostalgie poussiéreuse et qui peut ==se dupliquer de boutique en boutique==.",
        piloter: "On a ensuite piloté la phase de lancement pour que le nom, l'identité, le lieu et la communication ==arrivent ensemble==, cohérents et **prêts à être répliqués dès l'ouverture suivante**.",
        activer: "**Et on a créé le nom, Mary Madeleine, le logo et la charte graphique**, puis la communication de lancement avec les contenus, les shootings et l'animation des réseaux sociaux qui ont fait connaître l'enseigne ==dès ses premières semaines==.",
        resultat: "une enseigne **identifiable au premier coup d'œil**, un nom que l'on retient et une marque conçue dès le départ pour ==grandir en plusieurs adresses==." },
      logo: "arkt/images/marymadeleine-logo.jpg",
      photos: ["arkt/images/marymadeleine-1.jpg", "arkt/images/marymadeleine-2.jpg", "arkt/images/marymadeleine-3.jpg", "arkt/images/marymadeleine-4.jpg"],
      tags: ["Naming", "Identité visuelle", "Communication", "Lancement"],
      body: "Rendre la madeleine désirable et digne d'une enseigne à part entière." },
    { id: "bartpucci", name: "Bart & Pucci", year: "2023", phr: "4/5", short: "Design d'espace · filiale ARKT",
      story: { clarifier: "Bart & Pucci est né d'un constat fait sur nos propres missions : **une marque ne s'arrête pas à son logo, elle se vit dans un lieu**. En association avec Camille Puccinelli, on a créé une filiale dédiée à l'agencement et au design d'espace. On a d'abord clarifié son rôle : prolonger le travail stratégique d'ARKT ==jusque dans les murs==, pour que le positionnement d'une marque se ressente ==dès qu'on pousse la porte==.",
        piloter: "On a ensuite piloté son développement comme une marque à part entière, avec **deux clientèles distinctes à tenir ensemble** : ==les professionnels==, pour la création de lieux et la scénographie et ==les particuliers==, pour la rénovation et la gestion des travaux.",
        activer: "Et on a créé son identité, son offre et sa présence, avec les contenus et l'animation des réseaux sociaux qui donnent à voir ==les lieux réalisés== et qui font de **chaque chantier livré une preuve de plus**.",
        resultat: "une structure qui permet à ARKT d'accompagner ses clients **de la stratégie jusqu'à l'espace physique** et une expertise design qui alimente en retour ==tous les projets retail== de l'agence." },
      logo: "arkt/images/bartpucci-logo.jpg",
      photos: ["arkt/images/bartpucci-1.jpg", "arkt/images/bartpucci-2.jpg", "arkt/images/bartpucci-3.jpg"],
      tags: ["Design d'espace", "Scénographie", "Architecture intérieure"],
      body: "Prolonger la stratégie de marque jusque dans les murs." },
    { id: "selency", name: "Selency", year: "2019", phr: "4/5", short: "Marketplace mobilier · pôle B2B",
      story: { clarifier: "Selency, marketplace de mobilier vintage, avait une clientèle de particuliers solide et **un potentiel inexploité du côté des professionnels** : hôtels, bureaux, architectes et décorateurs. On a d'abord clarifié ce que serait ce ==pôle B2B== : à qui il s'adresse, ce qu'il promet et une stratégie de développement chiffrée, avec ==un prévisionnel qui engage== plutôt qu'une intuition.",
        piloter: "**On a ensuite piloté sa construction de zéro**, en tenant ==tous les leviers en même temps== : marketing, commercial, recrutement, finance et logistique, avec les arbitrages que suppose un service qui n'existait pas la veille.",
        activer: "**Et on a créé le service lui-même** : l'offre professionnelle, les outils et les process de vente, l'équipe et les actions marketing et commerciales qui ont fait connaître Selency auprès de ==l'hospitality, des bureaux et des prescripteurs==.",
        resultat: "**un pôle B2B parti de rien, devenu un levier de croissance stratégique** pour la marque et une expérience qui a forgé la méthode d'ARKT : ==construire, mesurer et faire durer==." },
      logo: "arkt/images/selency-logo.jpg",
      photos: ["arkt/images/selency-1.jpg", "arkt/images/selency-2.jpg", "arkt/images/selency-3.jpg"],
      tags: ["Développement commercial", "Stratégie", "B2B"],
      body: "Construire de zéro le pôle B2B d'une marketplace de mobilier." },
    { id: "vestiairecollective", name: "Vestiaire Collective", year: "2017", phr: "4/5", short: "Marketplace luxe · acquisition & CRM",
      story: { clarifier: "Vestiaire Collective, marketplace de mode de luxe de seconde main, avec un défi propre aux plateformes : **faire grandir en même temps deux audiences qui dépendent l'une de l'autre**, ==les vendeurs et les acheteuses==. On a d'abord clarifié les priorités d'acquisition et d'engagement pour chacune : qui recruter, qui réactiver, à quel coût et avec quel message, pour que les deux côtés de la marketplace avancent ==au même rythme==.",
        piloter: "On a ensuite piloté la stratégie d'acquisition et de CRM dans la durée, en arbitrant en continu entre les canaux, ==digitaux comme physiques==, **selon ce qui produisait réellement des ventes et pas seulement du trafic**.",
        activer: "**Et on a créé les campagnes elles-mêmes** : ==CRM== et campagnes in-app, Ads, SEA et SEO côté digital, ==événementiel et gifting== côté physique, avec les contenus qui les portaient.",
        resultat: "une expérience à l'échelle d'==une plateforme internationale==, qui a forgé la méthode qu'ARKT applique aujourd'hui à des entreprises de toutes tailles : **partir du business, mesurer et n'activer que ce qui sert la croissance**." },
      logo: "arkt/images/vestiairecollective-logo.jpg",
      photos: ["arkt/images/vestiairecollective-1.jpg", "arkt/images/vestiairecollective-2.jpg", "arkt/images/vestiairecollective-3.jpg"],
      tags: ["Acquisition", "CRM", "Communication"],
      body: "Faire grandir ensemble les deux audiences d'une marketplace de luxe." },
  ],

  /* ---------- approche ---------- */
  approche: [
    { k: "01", t: "Analyse & diagnostic", d: "Comprendre le contexte, les enjeux, les objectifs, les contraintes. Avant tout, écouter." },
    { k: "02", t: "Structuration stratégique", d: "Positionnement, messages clés, angles de prise de parole, priorités. Donner une direction claire." },
    { k: "03", t: "Activation", d: "Mise en œuvre ciblée et cadrée, toujours alignée sur la stratégie. Là où la trajectoire prend vie.", opt: true },
  ],

  /* ---------- offre ----------
     3 offres en cartes. Un clic sur une carte ouvre un panneau `detail` sous les cartes :
     pains (les galères du dirigeant, dans ses mots), faire (ce qu'on fait, sans jargon),
     change (ce que ça change pour lui), puis un bouton vers le contact.
  */
  offreLead: "Trois façons de travailler ensemble, selon où vous en êtes : clarifier la direction, piloter dans la durée, activer ce qui a été décidé.",
  offre: [
    { id: "clarifier", name: "Clarifier", sub: "One-shot stratégique",
      quand: "Vous lancez un projet, repositionnez une marque, ou sentez que « ça part dans tous les sens ». Vous voulez arrêter de décider à l'instinct.",
      contenu: ["Diagnostic", "Positionnement", "Messages clés", "Priorités", "Angles de communication"],
      fin: "Une direction claire, et de quoi trancher.",
      detail: {
        pains: [
          "Vous lancez quelque chose et vous ne savez pas par où commencer.",
          "Vous faites plein de choses, mais vous avez l'impression que rien n'avance vraiment.",
          "Votre marque ne ressemble plus à ce que vous êtes devenu.",
          "Vous décidez au feeling, et vous sentez que ça vous coûte.",
        ],
        faire: "On prend le temps de comprendre votre activité, vos clients, et ce qui vous rend différent. Puis on met des mots simples dessus : ce que vous proposez, à qui, et pourquoi on devrait vous choisir vous. On termine par une restitution, en direct, où tout devient clair.",
        change: "Vous savez où vous allez. Vous pouvez dire non aux mauvaises idées. Et chaque euro que vous dépenserez ensuite en communication servira à quelque chose.",
      } },
    { id: "piloter", name: "Piloter", sub: "Direction marketing externalisée",
      quand: "Vous avez une équipe ou des prestataires, mais pas de cap clair ni de pilotage. Les actions s'enchaînent sans cohérence.",
      contenu: ["Points mensuels de pilotage", "Arbitrages", "Validation des actions", "Cohérence globale", "Coordination des parties prenantes"],
      fin: "Un cerveau stratégique externalisé : arbitrage, priorisation, décision.",
      detail: {
        pains: [
          "Vous avez un freelance, une agence, un alternant… mais personne ne coordonne.",
          "Vous passez vos soirées à valider des posts au lieu de diriger votre boîte.",
          "Chaque prestataire tire dans sa direction, et vous au milieu.",
          "Vous ne savez pas si ce que vous payez sert vraiment à quelque chose.",
        ],
        faire: "On devient votre directeur marketing, sans que vous ayez à en embaucher un. Chaque mois, on regarde ensemble ce qui a été fait, ce qui marche, et on décide de la suite. Entre deux, c'est nous qui parlons à vos prestataires, qui tranchons, et qui disons non à ce qui ne sert pas votre cap.",
        change: "Vous retrouvez du temps. Il n'y a plus qu'une seule direction. Et vous arrêtez de payer pour des choses qui ne servent à rien.",
      } },
    { id: "activer", name: "Activer", sub: "Exécution cadrée",
      quand: "Vous voulez un interlocuteur unique et éviter la dispersion entre prestataires.",
      contenu: ["Contenu & community management", "Identité visuelle & charte graphique", "Site internet"],
      fin: "Toujours dans le prolongement d'un cadrage stratégique.",
      detail: {
        pains: [
          "Vous voulez un site, des contenus, une identité… mais pas gérer trois prestataires.",
          "Vous avez déjà eu un logo ou un site qui « ne ressemblait à rien », parce que personne n'avait de vision d'ensemble.",
          "Vous voulez que ce soit fait, bien fait, sans y passer vos soirées.",
        ],
        faire: "On produit ce qui a été décidé, avec des gens qu'on connaît et qu'on pilote : contenus et réseaux sociaux, identité visuelle, site internet. Vous avez un seul interlocuteur, un planning clair, et un aller-retour pour ajuster. Et comme on connaît votre stratégie, tout est cohérent dès le départ.",
        change: "C'est fait, c'est cohérent, et vous n'avez qu'un seul numéro à appeler.",
      } },
  ],

  /* ---------- témoignages (verbatims réels) ---------- */
  testimonials: [
    { name: "Julien Raynal", role: "CEO de Twicy", img: "https://framerusercontent.com/images/zE2BUbJcEjtHSkGL4KeMPa2SGho.png?width=828&height=782",
      quote: "Travailler avec ARKT est un vrai atout pour Twicy. Leur capacité à s'immerger rapidement dans notre business model leur permet de produire des contenus qui apportent une réelle valeur à nos clients : ils comprennent notre activité, nos enjeux et nos partenaires, avec une fluidité impressionnante, comme s'ils faisaient partie intégrante de l'entreprise. ARKT est un partenaire clé pour notre croissance.",
      hi: ["un vrai atout pour Twicy", "comme s'ils faisaient partie intégrante de l'entreprise", "un partenaire clé pour notre croissance"] },
    { name: "Maxime Brousse", role: "CEO de Selency", img: "https://framerusercontent.com/images/TybSV8UwyID2kF9mPEmMzyQQjA.webp?width=258&height=246",
      quote: "Arthur a construit le service pro de Selency, un pôle stratégique devenu un véritable levier de croissance pour la marque. Je le recommande pour sa capacité à innover, construire et pérenniser des projets complexes et stratégiques.",
      hi: ["un véritable levier de croissance", "innover, construire et pérenniser"] },
    { name: "Barbara Adinany", role: "CEO de L'Instant Cryo", img: "https://framerusercontent.com/images/sOBFIcV4MtSCAIFtHtmi0ElYmA.jpg?width=764&height=1135",
      quote: "Arthur possède une expertise dingue en matière de conception et développement stratégique. Grâce à sa grande capacité à comprendre mes besoins, nos collaborations régulières sont fluides et efficaces.",
      hi: ["une expertise dingue", "fluides et efficaces"] },
    { name: "Christophe Alloun", role: "Fondateur de Vé!", img: "https://framerusercontent.com/images/ABvRzJ5B6cOy4isg2lH8O3YAmY.png?width=470&height=481",
      quote: "Quand on a décidé d'ouvrir notre glacier, on nous a tout de suite recommandé ARKT pour créer notre identité. Nous savions exactement ce que nous ne voulions pas, et Arthur a parfaitement compris ce qu'il nous fallait. Chaque fois que j'entends « Vé, ton glacier comme il est beau », je dis merci Arthur.",
      hi: ["on nous a tout de suite recommandé ARKT", "a parfaitement compris ce qu'il nous fallait"] },
  ],

  /* ---------- équipe ---------- */
  team: [
    { name: "Arthur Barret", role: "Founder & CEO", img: "https://framerusercontent.com/images/rb4UNclQQsvqth0gNNBep2r4jHg.png?width=1436&height=1434",
      bio: "+10 ans à la tête de directions marketing & commerciales : Vestiaire Collective, Selency. Cofondateur du concept food La Meulerie." },
    { name: "Tobias Simon", role: "Consultant Marketing", img: "https://framerusercontent.com/images/XXlxtuXS3aS1YGtBgxtvWp8eA.jpeg?width=717&height=601",
      bio: "Coordination clients, gestion des projets récurrents, growth strategy." },
    { name: "Mickaël Guagenti", role: "Consultant Marketing", img: "https://framerusercontent.com/images/wwCV3juDZzvq7vIgGLzKbvVCtM.jpeg?width=800&height=800",
      bio: "Création de contenu vidéo & réseaux sociaux, stratégie marketing, DA." },
    { name: "Driss Azzoug", role: "Consultant Pop Culture", img: "https://framerusercontent.com/images/CjN28LCNrCmOmsN9OiwjmEZaU.jpg?width=656&height=686",
      bio: "Veille pop culture, direction créative." },
  ],
};
